# Generated by Django 4.2.10 on 2024-02-25 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Режиссер')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Режиссер',
                'verbose_name_plural': 'Режиссеры',
                'db_table': 'director',
            },
        ),
        migrations.CreateModel(
            name='MovieGenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='Жанр')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='Название фильма')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание фильма')),
                ('image', models.ImageField(upload_to='films_images', verbose_name='Постер фильма')),
                ('release_date', models.DateTimeField(verbose_name='Дата выхода фильма')),
                ('score', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Моя оценка фильму')),
                ('has_movie_released', models.BooleanField(default=False)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.directors', verbose_name='Режиссер фильма')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.moviegenres', verbose_name='Жанр фильма')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'db_table': 'film',
            },
        ),
    ]
