# Generated by Django 4.2.10 on 2024-02-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='release_date',
            field=models.DateField(verbose_name='Дата выхода фильма'),
        ),
    ]
