# Generated by Django 4.2.10 on 2024-02-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_films', '0002_alter_films_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выхода фильма'),
        ),
        migrations.AlterField(
            model_name='films',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='URL'),
        ),
    ]
