# Generated by Django 4.2.10 on 2024-02-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_films', '0004_alter_films_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='films_images', verbose_name='Постер фильма'),
        ),
    ]
